### PR TITLE
Compiling mongo on version 3.2.22 failed

### PR DESCRIPTION
**Pull request by Ccaomei**
Mongo failed to compile on version 3.2.22，The operation instruction is scons --prefix=/home/weilh/mongodb_source/mongodb_s/mongo_install_3.2.22 install MONGO_VERSION=3.2.22 CCFLAGS=-march=armv8-a+crc； An error is “ error: undefined reference to '__wt_checksum_init' ”； and other info like this：“ Erratum 843419 found and fixed at "build/opt/mongo/db/commands/get_last_error.o", section 69, offset 0x00000000. ”

### CODE REVIEW

**Comment by dhatcher42** [comment]
Pull Requests are an opportunity for our community to contribute to the MongoDB codebase. As this is an issue you having instead, I recommend you reach out to our community by posting on the [mongodb-user group](https://groups.google.com/group/mongodb-user) or on [Stack Overflow with the {{mongodb}} tag](https://stackoverflow.com/questions/tagged/mongodb). If you still have issues, you can create a ticket at https://jira.mongodb.org.
